### ISSUE TITLE
[Bug] Each theme has low contrast areas that are difficult to read

### ISSUE THREAD

**Issue by AndydeCleyre** [mucommander/mucommander#1296]
### Is there an existing issue for this?

- [X] I have searched the existing issues (including the closed ones)

### Description

I'm using the KDE Plasma desktop with a dark theme, and muCommander 1.5.2 has some low-contrast, hard to read part of the interface in each of the available muCommander themes.

In the following table, 🟢 means good contrast and legible, ❌ means contrast is too low.

Theme  |  Surrounding Location Bar  |  Location Bar  |  Status Bar  |  Free Disk Space Meter
---  |  ---  |  ---  |  ---  |  ---
ClassicCommander  | ❌  |  ❌  |  ❌  |  🟢
Native  |  ❌  |  🟢  |  🟢  |  ❌ 
RetroCommander  | ❌  |  ❌  |  🟢  |  ❌
SolarizedDark  | ❌  |  🟢  |  🟢  |  ❌
SolarizedLight  | ❌  |  🟢  |  🟢  |  ❌
Striped  | ❌  |  ❌  |  ❌  |  🟢

### Steps to reproduce

Use KDE Plasma with a dark theme, such as Breeze Dark, and try each muCommander theme.

### Expected behavior

One or more themes should be legible in every area of the UI.

### Actual behavior

Some UI areas offer very low contrast, making it hard to read the text there.

### Screenshots?

https://github.com/user-attachments/assets/9b379169-99fa-4a67-acf8-b3af7a7b5a21

The video is a little extra awkward because I expected `alt`+`w` to open the Window menu, but it seems those menus don't work that way.

### muCommander version

```yaml
Version: 1.5.2
Build date: 2024/10/18
Build number: cff7140
```

### Java version

```yaml
Runtime version: 23-internal
VM name: OpenJDK 64-Bit Server VM
VM version: 23-internal-ahadas-111c45cc11c21aeec4bdb9ff59e6b021b865754b
VM vendor: Oracle Corporation
```

### Operating System type and version

```yaml
Name: Linux
Version: 6.9.3-76060903-generic
Architecture: amd64
```
